# Generated by Django 4.0.4 on 2022-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conspect',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
