# Generated by Django 4.0.4 on 2022-04-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_user_message_author_conspect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conspect',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='conspect',
            name='title',
        ),
        migrations.RemoveField(
            model_name='conspect',
            name='updated',
        ),
    ]
