# Generated by Django 4.0.4 on 2022-05-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_remove_message_conspect_alter_classroom_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
