# Generated by Django 4.0.4 on 2022-05-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveSmallIntegerField(default=300),
        ),
    ]
