# Generated by Django 4.0.4 on 2022-06-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_conspect_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="description",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="conspect",
            name="description",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
